version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: sophtour_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - sophatour:/var/lib/mysql

volumes:
  sophatour:

